### PR TITLE
Word2vec

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
Added support for Word2vec and created relative test suite.

Created also CorpusTransformer, a simple tokenizer that handles synonyms, Porter stemming and stopwords.

In this pull request, additionally, we also have updated the library to support and leverage the latest updates we made to EnsmallenGraph.

### CODE REVIEW

**Comment by pnrobinson** [comment]
Thanks, Luca! We are at a survival camp today, I will look tomorrow!

**Comment by LucaCappelletti94** [comment]
Guys any feedback on this pull request?

**Comment by pnrobinson** [comment]
I think the setup script needs some work. I was having some issues and cloned the enture repository, and switched to this branch. Then I did the following
```
virtualenv p38
source p38/bin/activate
python setup.py install
(...)

Installed /home/peter/PycharmProjects/embiggen/p38/lib/python3.8/site-packages/opt_einsum-3.3.0-py3.8.egg
error: numpy 1.19.1 is installed but numpy<1.19.0,>=1.16.0 is required by {'tensorflow'}
```
Previously I had to fix this by adding numpy=1.18 to the setup.py file.

**Comment by LucaCappelletti94** [comment]
> I think the setup script needs some work. I was having some issues and cloned the enture repository, and switched to this branch. Then I did the following
> 
> ```
> virtualenv p38
> source p38/bin/activate
> python setup.py install
> (...)
> 
> Installed /home/peter/PycharmProjects/embiggen/p38/lib/python3.8/site-packages/opt_einsum-3.3.0-py3.8.egg
> error: numpy 1.19.1 is installed but numpy<1.19.0,>=1.16.0 is required by {'tensorflow'}
> ```
> 
> Previously I had to fix this by adding numpy=1.18 to the setup.py file.

Hi Peter!

Avoid installing packages using `python setup.py install` but use `pip install .`.

What is your version of tensorflow? That error seems related to an old version in the environment.

We can talk about this later in the call.

**Comment by pnrobinson** [comment]
I am still getting an error
```
(....)
Successfully built embiggen
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.1 which is incompatible.

```

**Comment by LucaCappelletti94** [comment]
For the time being, could you manually install NumPy with `pip install numpy=1.18`? We'll try to figure out why this error does not appear in the Travis builds.

**Comment by pnrobinson** [comment]
I am getting lots of other errors and cannot install...let's talk at 1PM

**Pull request merged**
