### PR TITLE
Csv reader

### PR DESCRIPTION
**Pull request by pnrobinson**
We should prob merge the two feature branches and then repair the unit tests (two seem to be broken or I am doing something stupid) and then make a new tagged release for the prefinal runs?

### CODE REVIEW

**Comment by callahantiff** [comment]
> We should prob merge the two feature branches and then repair the unit tests (two seem to be broken or I am doing something stupid) and then make a new tagged release for the prefinal runs?

Which tests are not working for you? I just ran them without any error.

**Comment by pnrobinson** [comment]
@callahantiff I think it is actually probably related to my venv, no need to worry. I am trying to track it down.

**Comment by callahantiff** [comment]
> @callahantiff I think it is actually probably related to my venv, no need to worry. I am trying to track it down.

OK, happy to help you hunt it down if you can't find it.

Looks like we passed Travis. I should note that there are some minor `pylint` errors for a few scripts (see below). I can track them down now or we can pursue them post-merge. Do you have a preference?

```python

************* Module embiggen.glove
embiggen/glove.py:5:7: E1101: Module 'tensorflow' has no '__version__' member (no-member)
************* Module embiggen.link_prediction
embiggen/link_prediction.py:220:35: E1136: Value 'self.train_edge_embs.shape' is unsubscriptable (unsubscriptable-object)
embiggen/link_prediction.py:222:36: E1136: Value 'self.train_edge_embs.shape' is unsubscriptable (unsubscriptable-object)
embiggen/link_prediction.py:224:46: E1136: Value 'self.train_src_embs.shape' is unsubscriptable (unsubscriptable-object)
************* Module embiggen.neural_networks
embiggen/neural_networks.py:1:0: E0401: Unable to import 'tensorflow.keras.models' (import-error)
embiggen/neural_networks.py:2:0: E0401: Unable to import 'tensorflow.keras.layers' (import-error)
embiggen/neural_networks.py:3:0: E0401: Unable to import 'tensorflow.keras.callbacks' (import-error)
embiggen/neural_networks.py:4:0: E0401: Unable to import 'tensorflow.keras.metrics' (import-error)
************* Module embiggen.text_encoder
embiggen/text_encoder.py:1:0: E0401: Unable to import 'nltk' (import-error)
embiggen/text_encoder.py:10:0: E0401: Unable to import 'tensorflow.keras.preprocessing.text' (import-error)
************* Module embiggen.word2vec
embiggen/word2vec.py:602:62: E0602: Undefined variable 'x_test' (undefined-variable)
embiggen/word2vec.py:668:39: E1101: Instance of 'ContinuousBagOfWordsWord2Vec' has no 'next_batch' member (no-member)
```

**Comment by callahantiff** [comment]
Ok, all low-hanging fruit `pylint` errors are resolved. Additional work is need in the `link_prediction.py` and `word2vec.py` scripts.

Shall I merge and close the related issues?

**Comment by pnrobinson** [comment]
@callahantiff  Thanks so much! I would vote for merging and making a new tagged release in master. We can then do one final round of polishing prior top submission of the manuscript (if all goes well) and take care of  pylint/codacy etc issues.

**Comment by callahantiff** [comment]
Ok, sounds like a good plan to me. Will do first thing tomorrow!

**Comment by callahantiff** [comment]
Merging now and closing related issues.

**Pull request merged**
