### PR TITLE
Parallelize random walks

### PR DESCRIPTION
**Pull request by justaddcoffee**
Per our convo on the Embiggen call today, we can/should probably parallelize the random walks.

Still failing a few tests, @LucaCappelletti94 said he'd finish this on his end

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@LucaCappelletti94 looks good and works on my end, however I don't see an improvement in speed using for example this test: 

Current HEAD:
```
(venv) ~/PycharmProjects/N2V *parallelize_walks $ git log | head -1 
commit bd2cae74c9038015b3137f0b4459d806612d4ec3
(venv) ~/PycharmProjects/N2V *parallelize_walks $ time python runLinkPrediction_ppi.py --num-walks 100
 p=1, q=1, classifier= LR, word2vec_model=Skipgram, num_epochs=1, context_window =3, dimension=200, Validation=False
[SNIP]
simulating walks: 12.119189023971558 seconds
[SNIP]
real    1m41.335s
user    2m40.440s
sys     0m5.603s
```

Compare with current master commit: 
```
(venv) ~/PycharmProjects/N2V *parallelize_walks $ git co 11dc8855061dac1a38deec687f5ab533686acfda

(venv) ~/PycharmProjects/N2V *(HEAD detached at 11dc885) $ time python runLinkPrediction_ppi.py --num-walks 100
Using TensorFlow backend.
 p=1, q=1, classifier= LR, word2vec_model=Skipgram, num_epochs=1, context_window =3, dimension=200, Validation=False
[SNIP]
simulating walks: 20.219385147094727 seconds
[SNIP]
real    1m51.749s
user    2m24.326s
sys     0m3.912s
```

Does this just need to run on a higher num-walks to speed things up?

**Comment by LucaCappelletti94** [comment]
How many walks did you use? How big is the graph, when compared to one used in an actual run?

**Comment by justaddcoffee** [comment]
Hi @vidarmehr - if this looks okay, we will merge to develop, and you can maybe try a test run to see if this speeds things up? This should reduce runtime by 30-40%
@LucaCappelletti94

**Comment by pnrobinson** [comment]
It would probably be good to make another tagged release to master for a milestone like this!

**Comment by vidarmehr** [comment]
@justaddcoffee @LucaCappelletti94 Thanks a lot! I just ran link prediction on small tests on my machine. I will run the code on the cluster this afternoon.  I see that pull request is to merge this branch to master. Isn't it better to first merge it to develop and then master with new tagged release?

**Comment by justaddcoffee** [comment]
> I see that pull request is to merge this branch to master. Isn't it better to first merge it to develop and then master with new tagged release?

Yes, you are right, sorry @vidarmehr ! I just changed this to merge to develop

**Comment by justaddcoffee** [comment]
+1 thanks @vidarmehr @LucaCappelletti94 !

**Pull request merged**
