### PR TITLE
fixing display word.

### PR DESCRIPTION
**Pull request by pnrobinson**
Fixing display word issue. Possibly some additional work is needed but it is working now
https://github.com/monarch-initiative/embiggen/issues/187

### CODE REVIEW

**Comment by pnrobinson** [comment]
This is the problem -- the display words is also trying to add some less common words, but in this case the entire list of words is only about 100
```
 self.display_examples = np.append(valid_examples, random.sample(range(1000, 1000 + valid_window), num), axis=0)
```

**Comment by pnrobinson** [comment]
@vidarmehr I fixed the issue.
@LucaCappelletti94 This PR contains a fix of the display word function. Given the changes you are making we may not be able to merge it -- if there are issues I can fix again after we merge your branch. If we can it should be ready to go though.

**Comment by vidarmehr** [comment]
@pnrobinson Thanks, Peter! I added num_nearest_neighbors to parse_args with the default parameter 16. I am going to merge it to develop.

**Comment by callahantiff** [comment]
That's a smart solution @vidarmehr. Sorry I am late to chime in here. Sounds like you guys have everything covered?

**Comment by vidarmehr** [comment]
@callahantiff Oh, no worries. Yes. I think everything works properly now. Thanks Tiffany:)

**Pull request merged**
